### ISSUE TITLE
Game Script - Nier: Automata

### ISSUE THREAD

**Issue by ShadowVolt** [mathewthe2/Game2Text-GameScripts#1]
Attached below is the full Japanese text for Nier: Automata. 

I ripped all the text from the game (via unpacking the game's archives) and merged it all into one text file; then I stripped all the blank lines, got rid of all ID/meta info via regex, and finally removed all stray HTML-style tags. If needed, I could provide the unedited file, which is about 4-5x as large and includes the english lines.

In my limited testing with it in this software, it seems to work well, aside from some additional lag from the text search. 

(edit 2: appear to have fixed the problems with split lines, apparently the \n's indicated line breaks mid-dialogue, so reverted that change by just removing them instead of also adding a line break.)

(edit 3: was missing the in-game novellas, cleaned them by hand and added them to the end of the file.)

(edit 4: removed all duplicate lines, shortening it by around 5k lines. have not tested as of this edit, so i have kept both files.)

[Nier Automata v3.txt (dupes present)](https://github.com/mathewthe2/Game2Text-GameScripts/files/6488481/Nier.Automata.v3.txt)
[Nier Automata v4.txt (dupes removed)](https://github.com/mathewthe2/Game2Text-GameScripts/files/6510748/Nier.Automata.v4.txt)

**Comment by mathewthe2** [comment]
Do you mind removing repeat lines?

> **……**
**……９Ｓ。**
え？なんでしょう？
敬称は要らない。
え？
……私の名前に『さん』は付けなくていい。
は、はい……分かりました。
……あ、そうだ。
司令官が呼んでたから一緒に行きましょう。
２Ｂさ……いえ、２Ｂ。
９Ｓ……
司令官からの命令で、２Ｂさんのメンテナンスを担当する事になったんです。
これから定期的にチェックしますね。
……そう。
心配は要りませんよ？僕達９Ｓモデルは優秀な事で有名ですから。
……って自分で言う事じゃないか。
**……**
**……９Ｓ。**

**Comment by ShadowVolt** [comment]
Removed duplicate lines and updated main comment, replied in the other issue thread with some more thoughts.
https://github.com/mathewthe2/Game2Text-GameScripts/issues/2#issuecomment-844351894

**Comment by mathewthe2** [comment]
Added to repository
https://github.com/mathewthe2/Game2Text-GameScripts/commit/fadffda517e93a8a33d90a5b3ed8fb0e979bebb5

**Comment by ShadowVolt** [comment]
Played through the majority of the game using v4 of this with no problems; closing this issue now.
