### ISSUE TITLE
Chrono Trigger Game Script

### ISSUE THREAD

**Issue by tenaibms** [mathewthe2/Game2Text-GameScripts#7]
Here's my attempt at cleaning up the Chrono Trigger game script.
I haven't tested it yet but it should work somewhat
The first file is the cleaned script, the other is the uncleaned script, for those who want to analyze my efforts.
[ChronoTriggerJapaneseScript.txt](https://github.com/mathewthe2/Game2Text-GameScripts/files/7627818/ChronoTriggerJapaneseScript.txt)
[ChronoTriggerComprehensiveScript.txt](https://github.com/mathewthe2/Game2Text-GameScripts/files/7627820/ChronoTriggerComprehensiveScript.txt)

EDIT:
For some reason game2text isn't matching exact matches from the script, odd..

**Comment by 10ai** [comment]
Okay it seems that this script is kinda garbo for detecting multi-line stuff, sorry ^^

I'll keep working
